### ISSUE TITLE
Not working in Sitecore 7+

### ISSUE THREAD

**Issue by mahendram88** [istern/Sitecore-Fakes#6]
This is not working from Sitecore 7+ as the constructor is made internal in Database class.

Is there any workaround for this? I know Sitecore.Fakes (https://github.com/sergeyshushlyapin/Sitecore.FakeDb) is available, but there are 1000's of unit tests written using this Fakes in our project. So don't want to disturb already existing test cases.

**Comment by istern** [comment]
Hi Sorry for my VERY late answer.
There is no workaround yet, since the constructor for the database in Sitecore 7+ now i private. Sorry I'm looking for a solution.

**Comment by istern** [comment]
Now working with 8.2
